name: Build and Publish

on:
  push:
    branches:
      - main
  release:
    types: [published]
  pull_request: null

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        settings:
          - file: ubuntu24.04
            version: "24.04"
            latest: true
            arm64: true
          - file: ubuntu22.04
            version: "22.04"
            latest: false
            arm64: true
          - file: ubuntu20.04
            version: "20.04"
            latest: false
            arm64: true
          - file: ubuntu18.04
            version: "18.04"
            latest: false
            arm64: true

    steps:
      - name: Check out the project
        uses: actions/checkout@v7

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ secrets.DOCKER_NAMESPACE }}/ubuntu-dummy-desktop

      - name: Build and push dummy desktop with ubuntu ${{ matrix.settings.version }}
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ${{ matrix.settings.file }}.Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ matrix.settings.latest && format('{0}/ubuntu-dummy-desktop:latest,', secrets.DOCKER_NAMESPACE) || '' }}${{ format('{0}/ubuntu-dummy-desktop:{1}', secrets.DOCKER_NAMESPACE, matrix.settings.version) }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push dummy desktop with ubuntu ${{ matrix.settings.version }} arm64
        if: ${{ matrix.settings.arm64 }}
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ${{ matrix.settings.file }}.Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/tags/') }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            ARM64=arm64v8/
          tags: ${{ matrix.settings.latest && format('{0}/ubuntu-dummy-desktop:latest-arm64,', secrets.DOCKER_NAMESPACE) || '' }}${{ format('{0}/ubuntu-dummy-desktop:{1}-arm64', secrets.DOCKER_NAMESPACE, matrix.settings.version) }}
          labels: ${{ steps.meta.outputs.labels }}
