name: Build and Publish

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the project
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_NAMESPACE }}/ubuntu-dummy-desktop

      - name: Build and push dummy desktop with ubuntu 24.04
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ubuntu24.04.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_NAMESPACE }}/ubuntu-dummy-desktop:latest,${{ secrets.DOCKER_NAMESPACE }}/ubuntu-dummy-desktop:24.04
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push dummy desktop with ubuntu 22.04
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ubuntu22.04.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_NAMESPACE }}/ubuntu-dummy-desktop:22.04
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push dummy desktop with ubuntu 20.04
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ubuntu20.04.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_NAMESPACE }}/ubuntu-dummy-desktop:20.04
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push dummy desktop with ubuntu 18.04
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ubuntu18.04.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_NAMESPACE }}/ubuntu-dummy-desktop:18.04
          labels: ${{ steps.meta.outputs.labels }}